# Análisis de datos de actividad física

Alejandro Hermosillo García - A01634552
<br>
Ana Paula Ponce Dávila - A01620477
<br> 
Andrés Olvera Varela - A01639918

## Preprocesamiento de los Datos

### Librerías

In [58]:
import pandas as pd 
import numpy as np 
# -----------------------------------
from sklearn.preprocessing import StandardScaler
# -----------------------------------
from sklearn.model_selection import train_test_split, KFold, StratifiedKFold, GridSearchCV
# -----------------------------------
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
# -----------------------------------
from sklearn.svm import SVC
# -----------------------------------
from sklearn.neighbors import KNeighborsClassifier
# -----------------------------------
from sklearn.neural_network import MLPClassifier
# -----------------------------------
from sklearn.linear_model import LogisticRegression
# -----------------------------------
from sklearn.ensemble import RandomForestClassifier
# -----------------------------------
from sklearn.feature_selection import RFE
# -----------------------------------
import warnings
warnings.filterwarnings("ignore")

### Lectura de archivos 

In [2]:
df1 = pd.read_csv('P3_data_set.txt', delimiter = '\s+', header = None)
df2 = pd.read_csv('P4_data_set.txt', delimiter = '\s+', header = None)
df3 = pd.read_csv('P5_data_set.txt', delimiter = '\s+', header = None)
# ----------------------------------------------------------------------
df4 = pd.read_csv('P13_data_set.txt', delimiter = '\s+', header = None) 
df5 = pd.read_csv('P14_data_set.txt', delimiter = '\s+', header = None) 
df6 = pd.read_csv('P15_data_set.txt', delimiter = '\s+', header = None) 


### Revisión de valores nulos

In [3]:
df1.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
dtype: int64

In [4]:
df2.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
dtype: int64

In [5]:
df3.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
dtype: int64

In [6]:
df4.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
dtype: int64

In [7]:
df5.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
dtype: int64

In [8]:
df6.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
dtype: int64

### Tamaño de bases de datos

In [9]:
print(df1.shape)
print(df2.shape)
print(df3.shape)
print(df4.shape)
print(df5.shape)
print(df6.shape)

(198, 19)
(200, 19)
(200, 19)
(200, 19)
(185, 19)
(196, 19)


### Aleatorización de orden

No queremos que el orden de nuestros datos afecte el entrenamiento de los modelos.

In [10]:
sdf1 = df1.sample(frac=1)
sdf2 = df2.sample(frac=1)
sdf3 = df3.sample(frac=1)
sdf4 = df4.sample(frac=1)
sdf5 = df5.sample(frac=1)
sdf6 = df6.sample(frac=1)

### Fusión de base de datos

In [11]:
combo = [sdf1, sdf2, sdf3, sdf4, sdf5, sdf6]
df = pd.concat(combo, ignore_index=True)

In [12]:
df

0        1       2    3             4        5       6    7   \
0     2.0   3.1030  0.4500 -2.0  1.446793e-15   2.8255  0.3225 -2.0   
1     4.0  -0.4430  0.0950 -2.0  0.000000e+00   0.1200  0.0660 -2.0   
2     2.0  16.2850  9.1150 -2.0 -3.002411e-16   5.7210  1.5510 -2.0   
3     2.0  14.6835  4.8935 -2.0  0.000000e+00 -10.5115  2.2385 -2.0   
4     4.0   0.2790  0.0850 -2.0 -9.709932e-16  -9.5275  0.2295 -2.0   
...   ...      ...     ...  ...           ...      ...     ...  ...   
1174  1.0   5.1635  1.0195 -2.0  0.000000e+00   1.0430  0.5230 -2.0   
1175  4.0   3.0450  0.1900 -2.0  0.000000e+00  -9.1725  0.0605 -2.0   
1176  4.0   2.9670  0.0060 -2.0  1.110260e-13  -9.1220  0.0800 -2.0   
1177  1.0   7.6175  0.4575 -2.0  0.000000e+00  -7.1710  0.7080 -2.0   
1178  1.0   8.1415  1.8355 -2.0 -7.899502e-16   0.6260  0.8570 -2.0   

                8        9       10   11            12         13         14  \
0     2.172153e-15   7.4665  0.4225 -2.0  0.000000e+00   0.146944   0.202500   
1     0.000000e+00   9.9005  0.0085 -2.0 -3.135212e-13   0.006549   0.009025   
2     0.000000e+00   5.2390  4.9120 -2.0  0.000000e+00  60.289473  83.083225   
3     0.000000e+00   0.9285  1.1515 -2.0  0.000000e+00  17.376701  23.946342   
4     0.000000e+00   0.6035  0.1455 -2.0 -5.631723e-16   0.005243   0.007225   
...            ...      ...     ...  ...           ...        ...        ...   
1174 -5.820582e-16   7.5310  1.7860 -2.0 -7.795175e-16   0.754228   1.039380   
1175 -4.406428e-14   0.9060  0.9820 -2.0  1.758600e-16   0.026196   0.036100   
1176  0.000000e+00   1.1245  0.0865 -2.0  0.000000e+00   0.000026   0.000036   
1177 -1.876989e-15  12.0880  1.4580 -2.0 -1.862692e-15   0.151883   0.209306   
1178  8.819374e-17  17.9185  6.4735 -2.0 -8.381519e-16   2.444764   3.369060   

            15        16         17         18  
0     0.075472  0.104006   0.129533   0.178506  
1     0.003161  0.004356   0.000052   0.000072  
2     1.745628  2.405601  17.508335  24.127744  
3     3.636155  5.010882   0.962179   1.325952  
4     0.038220  0.052670   0.015362   0.021170  
...        ...       ...        ...        ...  
1174  0.198487  0.273529   2.314680   3.189796  
1175  0.002656  0.003660   0.699763   0.964324  
1176  0.004644  0.006400   0.005430   0.007482  
1177  0.363743  0.501264   1.542564   2.125764  
1178  0.532954  0.734449  30.409302  41.906202  

[1179 rows x 19 columns]

In [13]:
X = df.iloc[: , 1:]
y = df.iloc[: , 0]

## Evaluación de Modelos

In [14]:
kf = StratifiedKFold(n_splits = 10, shuffle = True)  

### SVC

#### Linear

In [15]:
y_test_l = []
y_pred_l = []
accuracy  = 0 
cont = 1

for train_index, test_index in kf.split(X, y):
    # Training phase
    X_train = X.iloc[train_index, :]
    y_train = y.iloc[train_index]
    clf_SVCL = SVC(kernel = 'linear')
    clf_SVCL.fit(X_train, y_train)
    # Test phase
    X_test = X.iloc[test_index, :]
    y_test = y.iloc[test_index]    
    
    y_pred = clf_SVCL.predict(X_test)
    
    y_test_l.extend(y_test)
    y_pred_l.extend(y_pred)
    
    print('Exactitud en Fold', cont)
    print(accuracy_score(y_test, y_pred))
    print('-'*25)
    accuracy += accuracy_score(y_test, y_pred)
    cont += 1

print('Precisión por Clase')    
print(precision_score(y_test_l, y_pred_l, average = None))
print('Recall por Clase') 
print(recall_score(y_test_l, y_pred_l, average = None))
print('Exactitud promedio del modelo ')
accSVCL = accuracy/10
print(accSVCL)

Exactitud en Fold 1
0.7372881355932204
-------------------------
Exactitud en Fold 2
0.7288135593220338
-------------------------
Exactitud en Fold 3
0.7033898305084746
-------------------------
Exactitud en Fold 4
0.7288135593220338
-------------------------
Exactitud en Fold 5
0.7627118644067796
-------------------------
Exactitud en Fold 6
0.7203389830508474
-------------------------
Exactitud en Fold 7
0.711864406779661
-------------------------
Exactitud en Fold 8
0.7627118644067796
-------------------------
Exactitud en Fold 9
0.7203389830508474
-------------------------
Exactitud en Fold 10
0.7264957264957265
-------------------------
Precisión por Clase
[0.66360856 0.7854251  0.62068966 0.88111888]
Recall por Clase
[0.75347222 0.64882943 0.66220736 0.86006826]
Exactitud promedio del modelo 
0.7302766912936405


#### RBF

In [32]:
y_test_l = []
y_pred_l = []
accuracy  = 0 
cont = 1

for train_index, test_index in kf.split(X, y):
    # Training phase
    X_train = X.iloc[train_index, :]
    y_train = y.iloc[train_index]
    clf_SVCR = SVC(kernel = 'rbf')
    clf_SVCR.fit(X_train, y_train)
    # Test phase
    X_test = X.iloc[test_index, :]
    y_test = y.iloc[test_index]    
    
    y_pred = clf_SVCR.predict(X_test)
    
    y_test_l.extend(y_test)
    y_pred_l.extend(y_pred)
    
    print('Exactitud en Fold', cont)
    print(accuracy_score(y_test, y_pred))
    print('-'*25)
    accuracy += accuracy_score(y_test, y_pred)
    cont += 1

print('Precisión por Clase')    
print(precision_score(y_test_l, y_pred_l, average = None))
print('Recall por Clase') 
print(recall_score(y_test_l, y_pred_l, average = None))
print('Exactitud promedio del modelo ')
accSVCR = accuracy/10
print(accSVCR)

Exactitud en Fold 1
0.7796610169491526
-------------------------
Exactitud en Fold 2
0.7966101694915254
-------------------------
Exactitud en Fold 3
0.7457627118644068
-------------------------
Exactitud en Fold 4
0.8050847457627118
-------------------------
Exactitud en Fold 5
0.7203389830508474
-------------------------
Exactitud en Fold 6
0.7372881355932204
-------------------------
Exactitud en Fold 7
0.8135593220338984
-------------------------
Exactitud en Fold 8
0.7372881355932204
-------------------------
Exactitud en Fold 9
0.6864406779661016
-------------------------
Exactitud en Fold 10
0.7264957264957265
-------------------------
Precisión por Clase
[0.68731563 0.84274194 0.63299663 0.88135593]
Recall por Clase
[0.80902778 0.69899666 0.62876254 0.88737201]
Exactitud promedio del modelo 
0.7548529624800812


### K-NN

In [31]:
y_test_l = []
y_pred_l = []
accuracy  = 0 
cont = 1

for train_index, test_index in kf.split(X, y):
    # Training phase
    X_train = X.iloc[train_index, :]
    y_train = y.iloc[train_index]
    clf_KNN = KNeighborsClassifier(n_neighbors = 7)
    clf_KNN.fit(X_train, y_train)
    # Test phase
    X_test = X.iloc[test_index, :]
    y_test = y.iloc[test_index]    
    
    y_pred = clf_KNN.predict(X_test)
    
    y_test_l.extend(y_test)
    y_pred_l.extend(y_pred)
    
    print('Exactitud en Fold', cont)
    print(accuracy_score(y_test, y_pred))
    print('-'*25)
    accuracy += accuracy_score(y_test, y_pred)
    cont += 1

print('Precisión por Clase')    
print(precision_score(y_test_l, y_pred_l, average = None))
print('Recall por Clase') 
print(recall_score(y_test_l, y_pred_l, average = None))
print('Exactitud promedio del modelo ')
accKNN = accuracy/10
print(accKNN)

Exactitud en Fold 1
0.8305084745762712
-------------------------
Exactitud en Fold 2
0.8305084745762712
-------------------------
Exactitud en Fold 3
0.7627118644067796
-------------------------
Exactitud en Fold 4
0.8305084745762712
-------------------------
Exactitud en Fold 5
0.8050847457627118
-------------------------
Exactitud en Fold 6
0.7457627118644068
-------------------------
Exactitud en Fold 7
0.7711864406779662
-------------------------
Exactitud en Fold 8
0.7627118644067796
-------------------------
Exactitud en Fold 9
0.7796610169491526
-------------------------
Exactitud en Fold 10
0.7777777777777778
-------------------------
Precisión por Clase
[0.73590504 0.79927007 0.75757576 0.86842105]
Recall por Clase
[0.86111111 0.73244147 0.66889632 0.90102389]
Exactitud promedio del modelo 
0.7896421845574386


### Multi-layer Perceptron

In [28]:
y_test_l = []
y_pred_l = []
accuracy  = 0 
cont = 1

for train_index, test_index in kf.split(X, y):
    # Training phase
    X_train = X.iloc[train_index, :]
    y_train = y.iloc[train_index]
    clf_MLP = MLPClassifier(hidden_layer_sizes=(100,100,100,100,100), max_iter = 10000)
    clf_MLP.fit(X_train, y_train)
    # Test phase
    X_test = X.iloc[test_index, :]
    y_test = y.iloc[test_index]    
    
    y_pred = clf_MLP.predict(X_test)
    
    y_test_l.extend(y_test)
    y_pred_l.extend(y_pred)
    
    print('Exactitud en Fold', cont)
    print(accuracy_score(y_test, y_pred))
    print('-'*25)
    accuracy += accuracy_score(y_test, y_pred)
    cont += 1

print('Precisión por Clase')    
print(precision_score(y_test_l, y_pred_l, average = None))
print('Recall por Clase') 
print(recall_score(y_test_l, y_pred_l, average = None))
print('Exactitud promedio del modelo ')
accMLP = accuracy/10
print(accMLP)

Exactitud en Fold 1
0.7542372881355932
-------------------------
Exactitud en Fold 2
0.7796610169491526
-------------------------
Exactitud en Fold 3
0.8559322033898306
-------------------------
Exactitud en Fold 4
0.8389830508474576
-------------------------
Exactitud en Fold 5
0.8220338983050848
-------------------------
Exactitud en Fold 6
0.7627118644067796
-------------------------
Exactitud en Fold 7
0.8135593220338984
-------------------------
Exactitud en Fold 8
0.7796610169491526
-------------------------
Exactitud en Fold 9
0.8305084745762712
-------------------------
Exactitud en Fold 10
0.7606837606837606
-------------------------
Precisión por Clase
[0.75080906 0.79359431 0.76975945 0.88590604]
Recall por Clase
[0.80555556 0.7458194  0.74916388 0.90102389]
Exactitud promedio del modelo 
0.7997971896276981


### Logistic Regression

In [25]:
y_test_l = []
y_pred_l = []
accuracy  = 0 
cont = 1

for train_index, test_index in kf.split(X, y):
    # Training phase
    X_train = X.iloc[train_index, :]
    y_train = y.iloc[train_index]
    clf_LR = LogisticRegression()
    clf_LR.fit(X_train, y_train)
    # Test phase
    X_test = X.iloc[test_index, :]
    y_test = y.iloc[test_index]    
    
    y_pred = clf_LR.predict(X_test)
    
    y_test_l.extend(y_test)
    y_pred_l.extend(y_pred)
    
    print('Exactitud en Fold', cont)
    print(accuracy_score(y_test, y_pred))
    print('-'*25)
    accuracy += accuracy_score(y_test, y_pred)
    cont += 1

print('Precisión por Clase')    
print(precision_score(y_test_l, y_pred_l, average = None))
print('Recall por Clase') 
print(recall_score(y_test_l, y_pred_l, average = None))
print('Exactitud promedio del modelo ')
accLR = accuracy/10
print(accLR)

Exactitud en Fold 1
0.711864406779661
-------------------------
Exactitud en Fold 2
0.7203389830508474
-------------------------
Exactitud en Fold 3
0.7288135593220338
-------------------------
Exactitud en Fold 4
0.7033898305084746
-------------------------
Exactitud en Fold 5
0.7542372881355932
-------------------------
Exactitud en Fold 6
0.6864406779661016
-------------------------
Exactitud en Fold 7
0.6864406779661016
-------------------------
Exactitud en Fold 8
0.7372881355932204
-------------------------
Exactitud en Fold 9
0.635593220338983
-------------------------
Exactitud en Fold 10
0.7094017094017094
-------------------------
Precisión por Clase
[0.65064103 0.76538462 0.58803987 0.83333333]
Recall por Clase
[0.70486111 0.66555184 0.59197324 0.87030717]
Exactitud promedio del modelo 
0.7073808489062726


### Random Forest

In [26]:
y_test_l = []
y_pred_l = []
accuracy  = 0 
cont = 1

for train_index, test_index in kf.split(X, y):
    # Training phase
    X_train = X.iloc[train_index, :]
    y_train = y.iloc[train_index]
    clf_RF = RandomForestClassifier()
    clf_RF.fit(X_train, y_train)
    # Test phase
    X_test = X.iloc[test_index, :]
    y_test = y.iloc[test_index]    
    
    y_pred = clf_RF.predict(X_test)
    
    y_test_l.extend(y_test)
    y_pred_l.extend(y_pred)
    
    print('Exactitud en Fold', cont)
    print(accuracy_score(y_test, y_pred))
    print('-'*25)
    accuracy += accuracy_score(y_test, y_pred)
    cont += 1

print('Precisión por Clase')    
print(precision_score(y_test_l, y_pred_l, average = None))
print('Recall por Clase') 
print(recall_score(y_test_l, y_pred_l, average = None))
print('Exactitud promedio del modelo ')
accRF = accuracy/10
print(accRF)

Exactitud en Fold 1
0.7796610169491526
-------------------------
Exactitud en Fold 2
0.7542372881355932
-------------------------
Exactitud en Fold 3
0.7711864406779662
-------------------------
Exactitud en Fold 4
0.8050847457627118
-------------------------
Exactitud en Fold 5
0.7966101694915254
-------------------------
Exactitud en Fold 6
0.7966101694915254
-------------------------
Exactitud en Fold 7
0.7457627118644068
-------------------------
Exactitud en Fold 8
0.8559322033898306
-------------------------
Exactitud en Fold 9
0.7966101694915254
-------------------------
Exactitud en Fold 10
0.7863247863247863
-------------------------
Precisión por Clase
[0.75328947 0.80071174 0.7015873  0.91397849]
Recall por Clase
[0.79513889 0.75250836 0.73913043 0.87030717]
Exactitud promedio del modelo 
0.7888019701579023


In [33]:
data = [accSVCL, accSVCR, accKNN, accMLP, accLR, accRF]
index = ['Linear SVC', 'RBF SVC', 'KNN', 'Multi-Layer Perceptron', 'Logistic Regression', 'Random Forest']
pd.DataFrame(data, index=index, columns=['Scores']).sort_values(ascending = False, by=['Scores'])

Scores
Multi-Layer Perceptron  0.799797
KNN                     0.789642
Random Forest           0.788802
RBF SVC                 0.754853
Linear SVC              0.730277
Logistic Regression     0.707381

## Obtención de Hiperparámetros

Cada uno de los modelos utilizados anteriormente utiliza hiperparámetros. A continuación se mencionarán los distintos tipos de modelos que se usaron y sus hiperparámetros:

**1. Support Vector Classifier**

Se utilizó este tipo de modelo dos veces durante la etapa de evaluación. Se usó dos veces precisamente por uno de sus hiperparámetros más importantes, el cual es el tipo de **kernel** que se va a utilizar. En este proyecto, se utilizaron un kernel de base radial y otro lineal, para ver cual sería más eficiente aunque hay varios tipos de kernels aparte de estos. Otro parámetro crítico es la penalización **C** que puede tomar un rango de valores y tiene un efecto dramático en la forma de las regiones resultantes para cada clase.

**2. K-Nearest Neighbors Classifier**

El hiperparámetro más importante de este modelo de clasificación es la cantidad de vecinos **n_neighbors** que se usaran. Otros hiperparámetros no tan significativos, pero aún así interesantes  incluyen a la contribución de los miembros del vecindario a través de diferentes ponderaciones **weights** y las distintas métricas de distancia para elegir la composición del vecindario **metric**.

**3. Multi-Layer Perceptron Classifier**

Un Perceptrón multicapa, al igual que la mayoría de las redes neuronales tiene varios hiperparámetros. Los más importantes son el número de capas ocultas y el número de unidades para cada capa oculta **hidden_layer_sizes**, la tasa de aprendizaje **learning_rate** y la función de activación para la capa oculta **activation**.


**4. Logistic Regression**

En este tipo de clasificador, realmente no hay hiperparámetros críticos para ajustar. Sin embargo, algunos hiperparámetros que pueden llegar a presentar cambios útiles en la exactitud son **solver**, el cual determina el algoritmo a utlizar en el problema de optimización, **penalty**, que dictamina el tipo de castigo a aplicar  y el parámetro **C** que controla la fuerza de la penalización.

**5. Random Forest Classifier**

El parámetro más importante es el número de características aleatorias para muestrear en cada punto de división **max_features**. Otro parámetro importante para el este tipo de clasificador es el número de árboles **n_estimators**. Idealmente, este parámetro debería incrementarse hasta que no se vea ninguna mejora adicional en el modelo. En este proyecto, el default de dicho parámetro fue suficiente para encontrar un aproximado del máximo rendimiento del modelo.

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 20)

In [60]:
MLP = MLPClassifier(max_iter = 10000)
parameters = {
    'hidden_layer_sizes': [(100,), (100,100), (50,100,50), (100,100,100), (100,50,100,50,100), (100,100,100,100,100), (400,400,400,400,400)],
    'activation': ['identity', 'logistic', 'tanh', 'relu'],
    'solver': ['lbfgs', 'sgd', 'adam'],
    'learning_rate': ['constant', 'invscaling', 'adaptive']
}

MLP_Gs = GridSearchCV(MLP, parameters, n_jobs = -1)
MLP_Gs.fit(X_train, y_train)

print(MLP_Gs.best_params_)
print(MLP_Gs.best_score_)

{'activation': 'logistic', 'hidden_layer_sizes': (400, 400, 400, 400, 400), 'learning_rate': 'invscaling', 'solver': 'adam'}
0.7308960936620511


In [61]:
y_test_l = []
y_pred_l = []
accuracy  = 0 
cont = 1

for train_index, test_index in kf.split(X, y):
    # Training phase
    X_train = X.iloc[train_index, :]
    y_train = y.iloc[train_index]
    clf_MLP2 = MLPClassifier(hidden_layer_sizes=(400,400,400,400,400), max_iter = 10000, activation = 'logistic', 
                            learning_rate = 'invscaling', solver = 'adam')
    clf_MLP2.fit(X_train, y_train)
    # Test phase
    X_test = X.iloc[test_index, :]
    y_test = y.iloc[test_index]    
    
    y_pred = clf_MLP2.predict(X_test)
    
    y_test_l.extend(y_test)
    y_pred_l.extend(y_pred)
    
    print('Exactitud en Fold', cont)
    print(accuracy_score(y_test, y_pred))
    print('-'*25)
    accuracy += accuracy_score(y_test, y_pred)
    cont += 1

print('Precisión por Clase')    
print(precision_score(y_test_l, y_pred_l, average = None))
print('Recall por Clase') 
print(recall_score(y_test_l, y_pred_l, average = None))
print('Exactitud promedio del modelo ')
accMLP2 = accuracy/10
print(accMLP2)

Exactitud en Fold 1
0.788135593220339
-------------------------
Exactitud en Fold 2
0.847457627118644
-------------------------
Exactitud en Fold 3
0.8305084745762712
-------------------------
Exactitud en Fold 4
0.847457627118644
-------------------------
Exactitud en Fold 5
0.7627118644067796
-------------------------
Exactitud en Fold 6
0.8305084745762712
-------------------------
Exactitud en Fold 7
0.7966101694915254
-------------------------
Exactitud en Fold 8
0.7627118644067796
-------------------------
Exactitud en Fold 9
0.8135593220338984
-------------------------
Exactitud en Fold 10
0.8290598290598291
-------------------------
Precisión por Clase
[0.77631579 0.7807309  0.77351916 0.91637631]
Recall por Clase
[0.81944444 0.78595318 0.74247492 0.89761092]
Exactitud promedio del modelo 
0.8108720846008982


## Selección de Características

In [52]:
X_n = X.to_numpy()
y_n = y.to_numpy()
kf_n = KFold(n_splits=5, shuffle = True)

In [59]:
ks = np.arange(1, 10, 1)
accs = []
for k in ks:
    print('--------------- Filter-Wrapper feature selection, k =', k)    

    acc = 0
    rec = np.zeros(4)
    pre = np.zeros(4)
    for train_index, test_index in kf_n.split(X_n):
    
       # Training phase
        X_train = X_n[train_index, :]
        y_train = y_n[train_index]     

        rfe = RFE(clf_SVCL, n_features_to_select=k, step=1)
        rfe.fit(X_train, y_train)
        X_train = rfe.transform(X_train)

        clf_SVCL.fit(X_train, y_train)

        # Test phase
        X_test = rfe.transform(X_n[test_index, :])
        y_test = y_n[test_index]
        y_pred = clf_SVCL.predict(X_test)
    
        # Calculate confusion matrix and model performance
        cm = confusion_matrix(y_test, y_pred)
        acc += (cm[0,0]+cm[1,1]+cm[2,2]+cm[3,3])/len(y_test) 
    
        rec[0] += cm[0,0]/(cm[0,0]+cm[0,1]+cm[0,2]+cm[0,3])
        rec[1] += cm[1,1]/(cm[1,0]+cm[1,1]+cm[1,2]+cm[1,3])
        rec[2] += cm[2,2]/(cm[2,0]+cm[2,1]+cm[2,2]+cm[2,3])
        rec[3] += cm[3,3]/(cm[3,0]+cm[3,1]+cm[3,2]+cm[3,3])

        pre[0] += cm[0,0]/(cm[0,0]+cm[1,0]+cm[2,0]+cm[3,0])
        pre[1] += cm[1,1]/(cm[0,1]+cm[1,1]+cm[2,1]+cm[3,1])
        pre[2] += cm[2,2]/(cm[0,2]+cm[1,2]+cm[2,2]+cm[3,2])
        pre[3] += cm[3,3]/(cm[0,3]+cm[1,3]+cm[2,3]+cm[3,3])
    
    acc/=5
    rec/=5
    pre/=5
    print('ACC: ', acc)
    print('Recall: ', rec) 
    print('Precision: ', pre)

--------------- Filter-Wrapper feature selection, k = 1
ACC:  0.47583483591777853
Recall:  [0.0388322  0.5493709  0.42097507 0.87957444]
Precision:  [0.32833333 0.67640426 0.36589596 0.46271051]
--------------- Filter-Wrapper feature selection, k = 2
ACC:  0.5038189686260368
Recall:  [0.14418595 0.60140392 0.4217391  0.84828003]
Precision:  [0.36877173 0.68347186 0.36903188 0.52626506]
--------------- Filter-Wrapper feature selection, k = 3
ACC:  0.5089217454020916
Recall:  [0.20906234 0.59640769 0.37620775 0.86423156]
Precision:  [0.41341642 0.69367207 0.36267332 0.54598991]
--------------- Filter-Wrapper feature selection, k = 4
ACC:  0.5131373963216733
Recall:  [0.26212054 0.62710925 0.31723715 0.8447975 ]
Precision:  [0.40053467 0.68612868 0.36319599 0.54456315]
--------------- Filter-Wrapper feature selection, k = 5
ACC:  0.6149621348719798
Recall:  [0.32570691 0.66532367 0.59058651 0.86456172]
Precision:  [0.50587623 0.67057256 0.46385598 0.81152042]
--------------- Filter-Wrappe

Se puede observar que con tan solo 8 características se obtiene una exactitud muy cercana a la obtenida al correr el modelo con todas las características.

## Entrenamiento y prueba con distintas fuentes de datos 

Para esto nuevamente agruparemos las bases de datos, pero en esta ocasión por persona en vez de poner todas juntas.

In [39]:
combop1 = [sdf1, sdf2, sdf3]
combop2 = [sdf4, sdf5, sdf6]
dfp1 = pd.concat(combop1, ignore_index=True)
dfp2 = pd.concat(combop2, ignore_index=True)

In [42]:
Xp1 = dfp1.iloc[: , 1:]
Xp2 = dfp2.iloc[: , 1:]
yp1 = dfp1.iloc[: , 0]
yp2 = dfp2.iloc[: , 0]

### Multi-layer Perceptron

In [44]:
y_test_l = []
y_pred_l = []
accuracy  = 0 
cont = 1

for train_index, test_index in kf.split(Xp2, yp2):
    # Training phase
    X_train = Xp2.iloc[train_index, :]
    y_train = yp2.iloc[train_index]
    clf_MLP = MLPClassifier(hidden_layer_sizes=(100,100,100,100,100), max_iter = 10000)
    clf_MLP.fit(X_train, y_train)
    # Test phase
    X_test = Xp1.iloc[test_index, :]
    y_test = yp1.iloc[test_index]    
    
    y_pred = clf_MLP.predict(X_test)
    
    y_test_l.extend(y_test)
    y_pred_l.extend(y_pred)
    
    print('Exactitud en Fold', cont)
    print(accuracy_score(y_test, y_pred))
    print('-'*25)
    accuracy += accuracy_score(y_test, y_pred)
    cont += 1

print('Precisión por Clase')    
print(precision_score(y_test_l, y_pred_l, average = None))
print('Recall por Clase') 
print(recall_score(y_test_l, y_pred_l, average = None))
print('Exactitud promedio del modelo ')
accMLP = accuracy/10
print(accMLP)

Exactitud en Fold 1
0.576271186440678
-------------------------
Exactitud en Fold 2
0.4827586206896552
-------------------------
Exactitud en Fold 3
0.603448275862069
-------------------------
Exactitud en Fold 4
0.5344827586206896
-------------------------
Exactitud en Fold 5
0.4827586206896552
-------------------------
Exactitud en Fold 6
0.46551724137931033
-------------------------
Exactitud en Fold 7
0.5862068965517241
-------------------------
Exactitud en Fold 8
0.5862068965517241
-------------------------
Exactitud en Fold 9
0.4482758620689655
-------------------------
Exactitud en Fold 10
0.4827586206896552
-------------------------
Precisión por Clase
[0.46067416 0.44615385 0.38172043 0.76704545]
Recall por Clase
[0.28472222 0.4        0.4829932  0.93103448]
Exactitud promedio del modelo 
0.5248684979544126


### K-NN

In [45]:
y_test_l = []
y_pred_l = []
accuracy  = 0 
cont = 1

for train_index, test_index in kf.split(Xp2, yp2):
    # Training phase
    X_train = Xp2.iloc[train_index, :]
    y_train = yp2.iloc[train_index]
    clf_KNN = KNeighborsClassifier(n_neighbors = 7)
    clf_KNN.fit(X_train, y_train)
    # Test phase
    X_test = Xp1.iloc[test_index, :]
    y_test = yp1.iloc[test_index]    
    
    y_pred = clf_KNN.predict(X_test)
    
    y_test_l.extend(y_test)
    y_pred_l.extend(y_pred)
    
    print('Exactitud en Fold', cont)
    print(accuracy_score(y_test, y_pred))
    print('-'*25)
    accuracy += accuracy_score(y_test, y_pred)
    cont += 1

print('Precisión por Clase')    
print(precision_score(y_test_l, y_pred_l, average = None))
print('Recall por Clase') 
print(recall_score(y_test_l, y_pred_l, average = None))
print('Exactitud promedio del modelo ')
accKNN = accuracy/10
print(accKNN)

Exactitud en Fold 1
0.5423728813559322
-------------------------
Exactitud en Fold 2
0.4827586206896552
-------------------------
Exactitud en Fold 3
0.5689655172413793
-------------------------
Exactitud en Fold 4
0.6551724137931034
-------------------------
Exactitud en Fold 5
0.4827586206896552
-------------------------
Exactitud en Fold 6
0.4827586206896552
-------------------------
Exactitud en Fold 7
0.5172413793103449
-------------------------
Exactitud en Fold 8
0.5344827586206896
-------------------------
Exactitud en Fold 9
0.6551724137931034
-------------------------
Exactitud en Fold 10
0.5862068965517241
-------------------------
Precisión por Clase
[0.48979592 0.59649123 0.39534884 0.69035533]
Recall por Clase
[0.33333333 0.46896552 0.46258503 0.93793103]
Exactitud promedio del modelo 
0.5507890122735243


**¿Es posible entrenar un modelo de clasificación con los datos de un sujeto y obtener buenos resultados con los datos de otro sujeto? ¿Por qué?**

Si es posible. Esto se debe a que si uno entrena el modelo de clasificación con datos de un sujeto que realice las actividades de una manera parecida a como las realiza el otro sujeto, el modelo de clasificación si tendría buenos resultados. Sin embargo, como se ve en este ejercicio, si se tienen sujetos de distintas edades, géneros y condiciones físicas es muy complicado que el modelo de buenos resultados.

**¿Consideras que debes hacer ajustes cuando tengas datos de otro sujeto?**

Idealmente, al entrenar un modelo de clasificación se busca que la gente que ayude a proporcionar los datos sea una muestra poblacional para que el modelo funcione de manera global, con distintos tipos de sujetos. Este proyecto así se realizó y a lo mejor el único ajuste necesario puede ser un escalamiento de los datos. El inconveniente de esto es que la distribución de los datos puede presentar diferencias porque proviene de distintos sujetos. Otra opción, es entrenar distintos modelos para cada tipo de sujeto, pero esto toma más tiempo, se tienen menos datos y es más impráctico. 